version: '3.8'
services:
    mongodb:
      image: mongo:latest
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      ports:
        - "27017:27017"
      volumes:
        - ./data/mongo:/data/db
        - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      command: mongod --auth
      container_name: mongo
      networks:
        - app

    mongo-express:
      image: mongo-express:latest
      environment:
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_MONGODB_PORT: 27017
        ME_CONFIG_BASICAUTH_USERNAME: root
        ME_CONFIG_BASICAUTH_PASSWORD: root
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ports:
        - "8081:8081"
      container_name: mongo-express
      depends_on:
        - mongodb
      networks:
        - app

    backend:
      image: backend
      ports:
      - "3001:3001"
      build:
        context: ./Backend/
        dockerfile: Dockerfile
      container_name: backend
      depends_on:
      - mongodb
      networks:
      - app

    frontend:
      image: frontend
      ports:
      - "3000:3000"
      build:
        context: ./101388514_comp3123_assignment2_reactjs
        dockerfile: Dockerfile
      container_name: frontend
      volumes:
       - ./101388514_comp3123_assignment2_reactjs/src:/app/src
      depends_on:
      - mongodb
      networks:
      - app
      
networks:
  app:
